
# Generated by Django 5.2.4 on 2025-07-22 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('headache', 'Headache'), ('nausea', 'Nausea'), ('fatigue', 'Fatigue')], help_text='Type of symptom (e.g., headache, nausea, fatigue).', max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], help_text='Severity of the symptom: 1=Mild, 2=Moderate, 3=Severe.')),
                ('frequency', models.CharField(help_text='Frequency of the symptom (e.g., daily, weekly).', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the symptom was logged.')),
                ('user', models.ForeignKey(help_text='User who logged the symptom.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
