# Generated by Django 5.2.4 on 2025-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age.", null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase UID for authentication.', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='trimester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Current trimester (1, 2, or 3).', null=True),
        ),
    ]
